import "./globals.css";
import Link from "next/link";
import "../../styles/globals.css";
import Logo from "@/images/logo.svg";
import Image from "next/image";
import { CartProvider } from "../context/CartContext";
import CartButton from "@/component/CartButton/CartButton";
import { Button } from "@mui/material";
import { Suspense } from "react";
import Loading from "./loading";

export const metadata = {
  title: "Foodie",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <CartProvider>
          <header className="bg-gray-800 text-white p-4" style={{ position: 'sticky', zIndex: 1000, background: '#fff', top: 0}}>
            <div
              style={{
                display: "flex",
                flexDirection: "row",
                justifyContent: "space-between",
              }}
              className="container flex justify-between"
            >
              <Link style={{margin: 15}} href={"/"}>
                <Image src={Logo} width={200} height={200} alt="Fooedie eats" />
              </Link>
              <div
                style={{
                  display: "flex",
                  flexDirection: "row",
                }}
              >
                <Link href={"/menu"}>
                  <Button sx={{ m: 3, mr: 1 }} variant="outlined">
                    Menu
                  </Button>
                </Link>
                <CartButton />
              </div>
            </div>
          </header>
          <main className="container" style={{marginTop: '15px'}}>
            <Suspense fallback={<Loading />}>{children}</Suspense>
          </main>
        </CartProvider>
      </body>
    </html>
  );
}
