// import { Inter } from "next/font/google";
// import "./globals.css";

// const inter = Inter({ subsets: ["latin"] });

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

// export default function RootLayout({ children }) {
//   return (
//     <html lang="en">
//       <body className={inter.className}>{children}</body>
//     </html>
//   );
// }
// app/layout.js
// import Link from 'next/link'
// import '../../styles/globals.css'

// export default function RootLayout({ children }) {
//   return (
//     <html lang="en">
//       <body>
//         <header className="bg-gray-800 text-white p-4">
//           <nav>
//             <ul className="flex space-x-4">
//               <li><Link href="/">Home</Link></li>
//               <li><Link href="/menu">Menu</Link></li>
//               <li><Link href="/cart">Cart</Link></li>
//             </ul>
//           </nav>
//         </header>
//         <main>{children}</main>
//       </body>
//     </html>
//   )
// }

import { Inter } from "next/font/google";
import "./globals.css";
import Link from "next/link";
import "../../styles/globals.css";
import Logo from "@/images/logo.svg";
import Image from "next/image";
import { CartProvider } from "./context/CartContext";
import CartButton from "@/component/CartButton/CartButton";
import { Button } from "@mui/material";
import { Suspense } from "react";
import Loading from "./loading";

export const metadata = {
  title: "Foodie",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        {/* <header className="bg-gray-800 text-white p-4">
          <div style={{display:'flex', flexDirection:'row', justifyContent:'space-between'}} className="container flex justify-between">
            <Link href={"/"}>
              <Image src={Logo} width={200} height={200} alt="Fooedie eats" />
            </Link>
            <CartButton /> 
          </div>
        </header> */}
        <CartProvider>
          <header className="bg-gray-800 text-white p-4">
            <div
              style={{
                display: "flex",
                flexDirection: "row",
                justifyContent: "space-between",
              }}
              className="container flex justify-between"
            >
              <Link href={"/"}>
                <Image src={Logo} width={200} height={200} alt="Fooedie eats" />
              </Link>
              <div
                style={{
                  display: "flex",
                  flexDirection: "row",
                }}
              >
                <Link href={"/menu"}>
                  <Button sx={{ m: 2, mr: 1 }} variant="outlined">
                    Menu
                  </Button>
                </Link>
                <CartButton />
              </div>
            </div>
          </header>
          <main className="container">
            <Suspense fallback={<Loading />}>{children}</Suspense>
          </main>
        </CartProvider>
        {/* <footer className="bg-gray-900 py-12">
          <div className="container mx-auto flex items-center justify-between">
            <div className="flex-shrink-0">
              <Image src={Logo} width={200} height={200} alt="Fooedie eats" />
            </div>
            <div className="flex flex-col md:flex-row gap-8 text-gray-400 text-md">
              <a href="#" className="hover:text-gray-300">
                FAQ
              </a>
              <a href="#" className="hover:text-gray-300">
                Privacy Policy
              </a>
              <a href="#" className="hover:text-gray-300">
                Help & Support
              </a>
              <a href="#" className="hover:text-gray-300">
                Terms & Conditions
              </a>
            </div>
          </div>
        </footer> */}
      </body>
    </html>
  );
}
